<!DOCTYPE html>
<html
    class="dark"
    lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="UTF-8">
    <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0">
    <meta
        http-equiv="X-UA-Compatible"
        content="ie=edge">
    <title>Drive Accord - Your way fo finding solutions</title>
    <meta
        name="description"
        content="">
    <meta
        name="keywords"
        content="">

    <title>Laravel</title>

    <!-- Fonts -->
    <link
        rel="preconnect"
        href="https://fonts.bunny.net">
    <link
        href="https://fonts.bunny.net/css?family=figtree:400,500,600&display=swap"
        rel="stylesheet"/>

    <style>
        /* ----------------------------------------------
        * Generated by Animista
        * w: http://animista.net, t: @cssanimista
        * ---------------------------------------------- */

        .slide-in-bottom {
            -webkit-animation: slide-in-bottom .5s cubic-bezier(.25, .46, .45, .94) both;
            animation: slide-in-bottom .5s cubic-bezier(.25, .46, .45, .94) both
        }

        .slide-in-bottom-h1 {
            -webkit-animation: slide-in-bottom .5s cubic-bezier(.25, .46, .45, .94) .5s both;
            animation: slide-in-bottom .5s cubic-bezier(.25, .46, .45, .94) .5s both
        }

        .slide-in-bottom-subtitle {
            -webkit-animation: slide-in-bottom .5s cubic-bezier(.25, .46, .45, .94) .75s both;
            animation: slide-in-bottom .5s cubic-bezier(.25, .46, .45, .94) .75s both
        }

        .fade-in {
            -webkit-animation: fade-in 1.2s cubic-bezier(.39, .575, .565, 1.000) 1s both;
            animation: fade-in 1.2s cubic-bezier(.39, .575, .565, 1.000) 1s both
        }

        .bounce-top-icons {
            -webkit-animation: bounce-top .9s 1s both;
            animation: bounce-top .9s 1s both
        }

        @-webkit-keyframes slide-in-bottom {
            0% {
                -webkit-transform: translateY(1000px);
                transform: translateY(1000px);
                opacity: 0
            }
            100% {
                -webkit-transform: translateY(0);
                transform: translateY(0);
                opacity: 1
            }
        }

        @keyframes slide-in-bottom {
            0% {
                -webkit-transform: translateY(1000px);
                transform: translateY(1000px);
                opacity: 0
            }
            100% {
                -webkit-transform: translateY(0);
                transform: translateY(0);
                opacity: 1
            }
        }

        @-webkit-keyframes bounce-top {
            0% {
                -webkit-transform: translateY(-45px);
                transform: translateY(-45px);
                -webkit-animation-timing-function: ease-in;
                animation-timing-function: ease-in;
                opacity: 1
            }
            24% {
                opacity: 1
            }
            40% {
                -webkit-transform: translateY(-24px);
                transform: translateY(-24px);
                -webkit-animation-timing-function: ease-in;
                animation-timing-function: ease-in
            }
            65% {
                -webkit-transform: translateY(-12px);
                transform: translateY(-12px);
                -webkit-animation-timing-function: ease-in;
                animation-timing-function: ease-in
            }
            82% {
                -webkit-transform: translateY(-6px);
                transform: translateY(-6px);
                -webkit-animation-timing-function: ease-in;
                animation-timing-function: ease-in
            }
            93% {
                -webkit-transform: translateY(-4px);
                transform: translateY(-4px);
                -webkit-animation-timing-function: ease-in;
                animation-timing-function: ease-in
            }
            25%, 55%, 75%, 87% {
                -webkit-transform: translateY(0);
                transform: translateY(0);
                -webkit-animation-timing-function: ease-out;
                animation-timing-function: ease-out
            }
            100% {
                -webkit-transform: translateY(0);
                transform: translateY(0);
                -webkit-animation-timing-function: ease-out;
                animation-timing-function: ease-out;
                opacity: 1
            }
        }

        @keyframes bounce-top {
            0% {
                -webkit-transform: translateY(-45px);
                transform: translateY(-45px);
                -webkit-animation-timing-function: ease-in;
                animation-timing-function: ease-in;
                opacity: 1
            }
            24% {
                opacity: 1
            }
            40% {
                -webkit-transform: translateY(-24px);
                transform: translateY(-24px);
                -webkit-animation-timing-function: ease-in;
                animation-timing-function: ease-in
            }
            65% {
                -webkit-transform: translateY(-12px);
                transform: translateY(-12px);
                -webkit-animation-timing-function: ease-in;
                animation-timing-function: ease-in
            }
            82% {
                -webkit-transform: translateY(-6px);
                transform: translateY(-6px);
                -webkit-animation-timing-function: ease-in;
                animation-timing-function: ease-in
            }
            93% {
                -webkit-transform: translateY(-4px);
                transform: translateY(-4px);
                -webkit-animation-timing-function: ease-in;
                animation-timing-function: ease-in
            }
            25%, 55%, 75%, 87% {
                -webkit-transform: translateY(0);
                transform: translateY(0);
                -webkit-animation-timing-function: ease-out;
                animation-timing-function: ease-out
            }
            100% {
                -webkit-transform: translateY(0);
                transform: translateY(0);
                -webkit-animation-timing-function: ease-out;
                animation-timing-function: ease-out;
                opacity: 1
            }
        }

        @-webkit-keyframes fade-in {
            0% {
                opacity: 0
            }
            100% {
                opacity: 1
            }
        }

        @keyframes fade-in {
            0% {
                opacity: 0
            }
            100% {
                opacity: 1
            }
        }

    </style>

    <!-- Scripts -->
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body class="antialiased">
{{--<div class="relative sm:flex sm:justify-center sm:items-center min-h-screen bg-dots-darker bg-center bg-gray-100 dark:bg-dots-lighter dark:bg-gray-900 selection:bg-red-500 selection:text-white">--}}
{{--    @if (Route::has('login'))--}}
{{--        <livewire:welcome.navigation/>--}}
{{--    @endif--}}


<div
    class="h-screen bg-[url('/public/img/bg.jpg')] pb-14 bg-cover bg-left bg-gray-700 bg-blend-overlay"

>
    <!--Nav-->
    <div class="w-full flex container mx-auto p-6">

        <div class="w-full flex items-center justify-between">
            <a
                class="text-indigo-400 no-underline hover:no-underline font-bold text-2xl lg:text-4xl"
                href="/">
                <img
                    class="h-5"
                    src="{{asset('/img/logo.svg')}}"
                    alt="website logo">
            </a>

            <div class="flex w-1/2 justify-end content-center">
                <a
                    class="inline-block text-primary no-underline hover:text-primary-400 hover:text-underline text-center h-10 p-2 md:h-auto md:p-4"
                    data-tippy-content="@twitter_handle"
                    href="https://www.linkedin.com/in/abdulazizshebani"
                >
                    <svg
                        class="h-6 w-6 ring-primary-500 fill-primary text-primary stroke-primary "
                        viewBox="0 0 20 20"
                        xmlns="http://www.w3.org/2000/svg"
                    >
                        <g
                            id="SVGRepo_bgCarrier"
                            stroke-width="0"></g>
                        <g
                            id="SVGRepo_tracerCarrier"
                            stroke-linecap="round"
                            stroke-linejoin="round"></g>
                        <g id="SVGRepo_iconCarrier">
                            <title>linkedin [#161]</title>
                            <desc>Created with Sketch.</desc>
                            <defs></defs>
                            <g
                                id="Page-1"
                                stroke="none"
                                stroke-width="1"
                                fill="none"
                                fill-rule="evenodd">
                                <g
                                    id="Dribbble-Light-Preview"
                                    transform="translate(-180.000000, -7479.000000)"
                                    fill="#000000">
                                    <g
                                        id="icons"
                                        transform="translate(56.000000, 160.000000)">
                                        <path
                                            d="M144,7339 L140,7339 L140,7332.001 C140,7330.081 139.153,7329.01 137.634,7329.01 C135.981,7329.01 135,7330.126 135,7332.001 L135,7339 L131,7339 L131,7326 L135,7326 L135,7327.462 C135,7327.462 136.255,7325.26 139.083,7325.26 C141.912,7325.26 144,7326.986 144,7330.558 L144,7339 L144,7339 Z M126.442,7323.921 C125.093,7323.921 124,7322.819 124,7321.46 C124,7320.102 125.093,7319 126.442,7319 C127.79,7319 128.883,7320.102 128.883,7321.46 C128.884,7322.819 127.79,7323.921 126.442,7323.921 L126.442,7323.921 Z M124,7339 L129,7339 L129,7326 L124,7326 L124,7339 Z"
                                            id="linkedin-[#161]"></path>
                                    </g>
                                </g>
                            </g>
                        </g>
                    </svg>
                </a>
                <a
                    class="inline-block text-primary transition-all no-underline hover:text-primary-400 hover:text-underline text-center h-10 p-2 md:h-auto md:p-4 "
                    data-tippy-content="#facebook_id"
                    href="https://www.facebook.com/sharer/sharer.php?u=#">
                    <svg
                        class="fill-current h-6"
                        xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 32 32">
                        <path d="M19 6h5V0h-5c-3.86 0-7 3.14-7 7v3H8v6h4v16h6V16h5l1-6h-6V7c0-.542.458-1 1-1z"></path>
                    </svg>
                </a>
            </div>

        </div>

    </div>

    <!--Main-->
    <div class="container pt-24 md:pt-48 px-6 mx-auto flex flex-wrap flex-col md:flex-row content-center">

        <!--Left Col-->
        <div class="flex flex-col w-full xl:w-2/5 justify-center lg:items-start overflow-y-hidden">
            <h1 class="my-4 text-3xl md:text-5xl text-primary font-bold leading-tight text-center md:text-left slide-in-bottom-h1">
                Fix Your Car Problems with Expert Help from the Community!
            </h1>
            <p class="leading-normal dark:text-white/65 text-base md:text-2xl mb-8 text-center md:text-left slide-in-bottom-subtitle">
                Get free advice, share experiences, and learn from car enthusiasts at DriveAccord.
            </p>

            <p class="text-primary-300 font-bold pb-8 lg:pb-6 text-center md:text-left fade-in">Start contributing
                now!
            </p>
            <div class="flex w-full gap-2 justify-center md:justify-start pb-24 lg:pb-0 fade-in">
                @guest
                    <a href="/login">
                        <button class="rounded-md transition-all hover:bg-white/15 border-2 border-primary px-10 py-1.5 text-lg dark:text-white">
                            Log in
                        </button>
                    </a>
                    <a href="/register">
                        <button class="rounded-md bg-primary border-primary transition-all hover:bg-primary-400 px-10 py-1.5 text-lg dark:text-white">

                            Register
                        </button>
                    </a>
                @endguest

                @auth
                    <a href="/dashboard">
                        <button class="rounded-md bg-primary border-primary transition-all hover:bg-primary-400 px-10 py-1.5 text-lg dark:text-white">
                            Find a solution to your issue
                        </button>
                    </a>
                @endauth
            </div>

        </div>

        <!--Footer-->
        <div class="w-full pt-16 pb-6 text-sm text-center md:text-left fade-in">
            <p
                class="text-gray-500 no-underline hover:no-underline">
                Made by
                <a
                    href="https://www.linkedin.com/in/abdulazizshebani"
                    class="font-semibold"
                    target="_blank"
                >
                    Abdulaziz Shebani
                </a>
                in 2024
            </p>
        </div>

    </div>


</div>


<!-- jQuery if you need it
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
-->

{{--</div>--}}
</body>
</html>
